[package]
name = "bits"
version = "0.1.0"
edition = "2024"

[features]
default = []
# nightly = []

# [toolchain]
# channel = "stable"

[dependencies]

[dev-dependencies]
bitcoin = { version = "0.32.5", features = ["base64"] }
